# -*- coding: utf-8 -*-
"""Calcular_estacionalidad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13yzNtXqQQUWuhUdb-8U5My5a_ogD_w6G

Estacionalidad
"""

"""
Módulo para el Cálculo y Persistencia de Índices Estacionales Mensuales por Nivel 2.
"""
from pathlib import Path
import numpy as np
import pandas as pd


def compute_and_save_seasonality(
    ventas_path: str = "ventas.parquet",
    catalogo_path: str = "catalogo.parquet",
    output_path: str = "estacionalidad.parquet"
) -> pd.DataFrame:
    print("\n[+] Calculando matriz de estacionalidad por Nivel 2...")

    # 1. Carga columnar optimizada
    df_v = pd.read_parquet(ventas_path, columns=["Código Mercancía", "Cant. Venta", "fecha"])
    df_c = pd.read_parquet(catalogo_path, columns=["Código Mercancía", "Nivel 2"])

    # 2. Cruce relacional
    df = pd.merge(df_v, df_c, on="Código Mercancía", how="inner")
    df = df.dropna(subset=["fecha", "Nivel 2"])

    # Extraer variables temporales
    df["Mes"] = df["fecha"].dt.month.astype("int8")
    df["Anio_Mes"] = df["fecha"].dt.to_period("M")

    # Calcular días únicos con venta por mes registrado
    dias_por_periodo = df.groupby(["Nivel 2", "Anio_Mes", "Mes"])["fecha"].nunique().reset_index()
    dias_por_periodo.rename(columns={"fecha": "Dias_Activos"}, inplace=True)

    # 3. Suma de venta por periodo
    ventas_periodo = df.groupby(["Nivel 2", "Anio_Mes", "Mes"])["Cant. Venta"].sum().reset_index()

    # Unir ventas y días
    merged_temporal = pd.merge(ventas_periodo, dias_por_periodo, on=["Nivel 2", "Anio_Mes", "Mes"])

    # Venta diaria promedio por mes calendario observado
    merged_temporal["ADU_Mes"] = merged_temporal["Cant. Venta"] / merged_temporal["Dias_Activos"].clip(lower=1)

    # 4. Agrupar por Mes del año (1 al 12) promediando años si hay más de 1 año de datos
    estacionalidad = merged_temporal.groupby(["Nivel 2", "Mes"])["ADU_Mes"].mean().reset_index()

    # Promedio global de la categoría (denominador)
    avg_global = estacionalidad.groupby("Nivel 2")["ADU_Mes"].transform("mean")

    # Índice Estacional mensual
    estacionalidad["Factor_Estacional"] = np.where(
        avg_global > 0,
        estacionalidad["ADU_Mes"] / avg_global,
        1.0
    )

    # 5. Aplicar límites de control (Evita sobrestock y desabasto por anomalías)
    estacionalidad["Factor_Estacional"] = estacionalidad["Factor_Estacional"].clip(lower=0.40, upper=2.50).astype("float32")

    # 6. Completar meses faltantes con 1.0 para todas las categorías
    todas_categorias = df_c["Nivel 2"].dropna().unique()
    todos_meses = pd.DataFrame(
        [(cat, mes) for cat in todas_categorias for mes in range(1, 13)],
        columns=["Nivel 2", "Mes"]
    )

    matriz_completa = pd.merge(todos_meses, estacionalidad[["Nivel 2", "Mes", "Factor_Estacional"]], on=["Nivel 2", "Mes"], how="left")
    matriz_completa["Factor_Estacional"] = matriz_completa["Factor_Estacional"].fillna(1.0).astype("float32")

    # 7. Persistir en Parquet
    matriz_completa.to_parquet(output_path, engine="pyarrow", compression="snappy", index=False)

    print(f"[✓] Matriz de estacionalidad guardada en '{output_path}'.")
    print(f"    Categorías procesadas: {matriz_completa['Nivel 2'].nunique()}")
    print(f"    Rango de factores calculados: {matriz_completa['Factor_Estacional'].min():.2f}x a {matriz_completa['Factor_Estacional'].max():.2f}x\n")

    return matriz_completa


if __name__ == "__main__":
    compute_and_save_seasonality()