# -*- coding: utf-8 -*-
"""engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGr_RSKRQpRR7h54hzTrnGGksxn_gvgJ

Definición de funciones
"""

"""
Motor de Cálculo Logístico DSD con Estacionalidad Dinámica y Min-Max.
"""
from typing import Dict, Tuple
import numpy as np
import pandas as pd


class ReplenishmentEngine:
    def __init__(
        self,
        lead_time_days: int = 3,
        review_frequency_days: int = 7,
        extra_coverage_days: int = 2,
        min_cv: float = 0.50,
    ):
        self.lt = lead_time_days
        self.r = review_frequency_days
        self.cov_extra = extra_coverage_days
        self.min_cv = min_cv

        # Factores Z según nivel de servicio Pareto
        self.z_table: Dict[str, float] = {
            "A": 2.05,  # 98%
            "B": 1.65,  # 95%
            "C": 1.28,  # 90%
        }

    def compute_seasonal_indices(self, df_sales: pd.DataFrame) -> pd.DataFrame:
        """
        Calcula el índice de estacionalidad mensual por 'Nivel 2'.
        Si no hay suficiente profundidad histórica, retorna índice 1.0.
        """
        sales = df_sales.copy()
        sales["fecha"] = pd.to_datetime(sales["fecha"], format="%d/%m/%Y", errors="coerce")
        sales = sales.dropna(subset=["fecha", "Nivel 2"])

        if sales.empty or sales["fecha"].dt.month.nunique() <= 1:
            # Fallback neutral si la serie temporal no tiene más de un mes
            unique_cats = df_sales["Nivel 2"].dropna().unique()
            return pd.DataFrame({"Nivel 2": unique_cats, "Factor_Estacional": 1.0})

        sales["Mes"] = sales["fecha"].dt.month

        # Venta total mensual por categoría
        cat_month = sales.groupby(["Nivel 2", "Mes"])["Cant. Venta"].sum().reset_index()

        # Promedio mensual general de la categoría
        cat_avg = cat_month.groupby("Nivel 2")["Cant. Venta"].transform("mean")
        cat_month["Factor_Estacional"] = np.where(
            cat_avg > 0,
            cat_month["Cant. Venta"] / cat_avg,
            1.0
        )

        current_month = sales["fecha"].max().month
        current_seasonality = cat_month[cat_month["Mes"] == current_month][["Nivel 2", "Factor_Estacional"]]
        return current_seasonality

    def compute_pareto(self, df_data: pd.DataFrame) -> pd.DataFrame:
        """
        Calcula Pareto ABC dentro de cada tienda y Nivel 2.
        """
        df = df_data.copy()
        sku_vol = (
            df.groupby(["Establecimiento", "Nivel 2", "Código Mercancía"])["Cant. Venta"]
            .sum()
            .reset_index()
        )
        sku_vol = sku_vol.sort_values(
            by=["Establecimiento", "Nivel 2", "Cant. Venta"],
            ascending=[True, True, False]
        )

        sku_vol["total_cat"] = sku_vol.groupby(["Establecimiento", "Nivel 2"])["Cant. Venta"].transform("sum")
        sku_vol["pct_share"] = np.where(
            sku_vol["total_cat"] > 0,
            sku_vol["Cant. Venta"] / sku_vol["total_cat"],
            0.0
        )
        sku_vol["pct_acum"] = sku_vol.groupby(["Establecimiento", "Nivel 2"])["pct_share"].cumsum()

        conditions = [
            sku_vol["pct_acum"] <= 0.80,
            sku_vol["pct_acum"] <= 0.95,
        ]
        choices = ["A", "B"]
        sku_vol["Clase_ABC"] = np.select(conditions, choices, default="C")

        return sku_vol[["Establecimiento", "Código Mercancía", "Clase_ABC"]]

    def execute_min_max(self, df_merged: pd.DataFrame) -> pd.DataFrame:
        """
        Calcula demanda ajustada, SS, MIN, MAX y pedido sugerido.
        Aplica Piezas_Por_Caja = 1 si es proveedor Directo.
        """
        df = df_merged.copy()

        # 1. Parámetros directos vs cedis
        df["Factor_Empaque"] = np.where(
            df["Tipo de proveedor"].astype(str).str.upper() == "DIRECTO",
            1,
            df.get("Piezas_Caja", 1)
        )
        df["Transito"] = 0  # Regla operativa: no hay inventario en tránsito para DSD

        # 2. Demanda diaria ponderada
        factor_est = df.get("Factor_Estacional", 1.0)
        # Se normaliza la venta de la muestra como tasa diaria base
        df["Demanda_Diaria"] = (df["Cant. Venta"].fillna(0) * factor_est).clip(lower=0.0)

        # 3. Piso de variabilidad (CV mínimo = 0.50)
        df["Sigma_D"] = df["Demanda_Diaria"] * self.min_cv

        # 4. Inventario de Seguridad (SS)
        df["Factor_Z"] = df["Clase_ABC"].map(self.z_table).fillna(1.28)
        df["SS"] = np.ceil(df["Factor_Z"] * np.sqrt(self.lt) * df["Sigma_D"])

        # 5. Punto Mínimo (MIN)
        df["MIN"] = np.ceil((df["Demanda_Diaria"] * self.lt) + df["SS"])

        # 6. Punto Máximo (MAX)
        horizonte_max = self.r + self.cov_extra
        df["MAX"] = np.ceil(df["MIN"] + (df["Demanda_Diaria"] * horizonte_max))

        # 7. Necesidad Neta y Gatillo de Reorden (Existencia + Transito <= MIN)
        df["Existencia"] = pd.to_numeric(df["Existencia"], errors="coerce").fillna(0)
        df["Gatillo_Reorden"] = (df["Existencia"] + df["Transito"]) <= df["MIN"]

        df["Necesidad_Pzas"] = np.where(
            df["Gatillo_Reorden"],
            np.maximum(0, df["MAX"] - (df["Existencia"] + df["Transito"])),
            0.0
        )

        # 8. Unidades / Cajas a solicitar
        df["Unidades_Sugeridas"] = np.ceil(df["Necesidad_Pzas"] / df["Factor_Empaque"]) * df["Factor_Empaque"]
        df["Unidades_Sugeridas"] = df["Unidades_Sugeridas"].astype(int)

        # 9. Diagnóstico de inventario
        condiciones = [
            df["Existencia"] <= 0,
            df["Existencia"] <= df["SS"],
            df["Existencia"] <= df["MIN"],
            df["Existencia"] > df["MAX"],
        ]
        etiquetas = [
            "AGOTADO (Stockout)",
            "CRÍTICO (Bajo SS)",
            "REORDENAR (Bajo MIN)",
            "SOBRESTOCK"
        ]
        df["Estado_Inventario"] = np.select(condiciones, etiquetas, default="ÓPTIMO")

        return df