# -*- coding: utf-8 -*-
"""Explicación_reglas_surtido.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8uIQfT5iFHkv8WQFd64eCibM1oeaIUk
"""

"""
Módulo de Explicabilidad Logística (XAI) para Tiendas de Conveniencia.
Traduce parámetros del modelo Min-Max a diagnósticos en lenguaje natural.
"""
from typing import Dict, Any
import numpy as np


def generate_sku_narrative(row: Dict[str, Any], lead_time: int = 3, review_cycle: int = 7) -> Dict[str, Any]:
    """
    Genera el diagnóstico en lenguaje humano para un SKU específico.
    """
    demanda_base = float(row.get("Demanda_Diaria_Base", 0.0))
    factor_est = float(row.get("Factor_Estacional", 1.0))
    demanda_ajustada = float(row.get("Demanda_Ajustada", demanda_base * factor_est))
    existencia = float(row.get("Existencia", 0.0))
    ss = float(row.get("SS", 0.0))
    minimo = float(row.get("MIN", 0.0))
    maximo = float(row.get("MAX", 0.0))
    sugerido = int(row.get("Unidades_Sugeridas", 0))
    dias_cobertura = float(row.get("Dias_Cobertura", 0.0))
    clase_abc = str(row.get("Clase_ABC", "C"))

    # 1. Diagnóstico de velocidad de venta
    if demanda_base <= 0:
        ritmo_venta = "Este producto no ha registrado ventas en los últimos 60 días."
    else:
        ritmo_venta = f"Vendes en promedio **{demanda_base:.1f} piezas al día** (ritmo de los últimos 60 días)."

    # 2. Diagnóstico de temporada
    diff_estacional = round((factor_est - 1.0) * 100, 1)
    if diff_estacional > 0:
        temporada = f"🔥 **Mes de alta demanda:** Tu categoría tiene un incremento estacional del **+{diff_estacional}%** este mes."
    elif diff_estacional < 0:
        temporada = f"❄️ **Mes de baja demanda:** La categoría tiene un ajuste estacional del **{diff_estacional}%**."
    else:
        temporada = "⚖️ **Demanda regular:** La categoría no presenta variación estacional atípica este mes."

    # 3. Diagnóstico de cobertura de existencias
    if existencia <= 0:
        cobertura_msg = "🚨 **Stockout (Agotado):** No tienes piezas en tienda. Cada día que pasa se pierde venta."
    elif dias_cobertura <= lead_time:
        cobertura_msg = (
            f"⚠️ **Riesgo inminente:** Con **{existencia:.0f} piezas** tienes abasto para solo **{dias_cobertura:.1f} días**. "
            f"Como el proveedor tarda **{lead_time} días** en entregar, te quedarás en ceros antes de que llegue el camión."
        )
    elif dias_cobertura <= (lead_time + review_cycle):
        cobertura_msg = (
            f"🟡 **Cobertura justa:** Tienes inventario para **{dias_cobertura:.1f} días**. "
            f"Alcanzas a cubrir el tiempo de entrega pero entrarías a tu zona de reserva de seguridad."
        )
    else:
        cobertura_msg = f"🟢 **Stock saludable:** Tienes inventario suficiente para **{dias_cobertura:.1f} días**."

    # 4. Razón del gatillo de compra
    pareto_desc = {
        "A": "Producto Clase A (Top 80% de tus ventas): Tiene un nivel de servicio prioritario del 98% para evitar quiebres.",
        "B": "Producto Clase B (Venta media, 15% acumulado): Nivel de servicio intermedio del 95%.",
        "C": "Producto Clase C (Baja rotación): Nivel de servicio estándar del 90% para no congelar dinero en stock."
    }

    if sugerido > 0:
        razon_pedido = (
            f"El sistema solicita **{sugerido} piezas** porque tu stock actual ({existencia:.0f}) "
            f"cayó por debajo del Punto Mínimo ({minimo:.0f}). "
            f"El pedido de {sugerido} pzas te llevará al Punto Máximo ({maximo:.0f}), garantizando producto "
            f"para los **{lead_time} días de entrega** más los **{review_cycle} días** hasta la siguiente visita del proveedor, "
            f"protegiendo un colchón de seguridad de **{ss:.0f} piezas**."
        )
    else:
        razon_pedido = (
            f"El sistema **no sugiere pedir nada hoy** porque tu stock actual ({existencia:.0f} pzas) "
            f"es mayor que el Punto Mínimo ({minimo:.0f} pzas). Pedir producto ahora generaría sobrestock en tienda."
        )

    return {
        "ritmo_venta": ritmo_venta,
        "temporada": temporada,
        "cobertura_msg": cobertura_msg,
        "razon_pedido": razon_pedido,
        "pareto_info": pareto_desc.get(clase_abc, ""),
        "existencia": existencia,
        "minimo": minimo,
        "maximo": maximo,
        "ss": ss,
        "sugerido": sugerido,
        "post_pedido": existencia + sugerido
    }